grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 1

model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false

  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
      criterion:
      - mse
    search_param_grid:
      min_samples_leaf:
      - 6
      n_estimators:
      - 100
      max_depth:
      - 5

  module_2:
    class: DecisionTreeRegressor
    module: sklearn.tree
    params:
      criterion:
      - squared_error
      max_features:
      - None
    search_param_grid:
      criterion:
      - squared_error
      - friedman_mse
      - absolute_error
      - poisson
      max_features:
      - 'auto'
      - 'sqrt'
      - 'log2'
      max_depth : 4
  module_3:
    class:  GradientBoostingRegressor
    module: sklearn.ensemble
    params:
      criterion:
      - squared_error
      max_features:
      - None
    search_param_grid:
      criterion:
      - squared_error
      - friedman_mse
      max_features:
      - 'auto'
      n_estimators:
      - 100
      max_depth : 4  


  
      
